apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
    SMS_CONNECTION_STRING: {{ .Values.sms.connectionString | b64enc | quote }}
    SMS_FROM_NUMBER: {{ .Values.sms.fromNumber | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-listmonk
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  LISTMONK_HOST: {{ .Values.listmonk.hostname | b64enc | quote }}
  LISTMONK_USERNAME: {{ .Values.listmonk.username | b64enc | quote }}
  LISTMONK_PASSWORD: {{ .Values.listmonk.password | b64enc | quote }}